apiVersion: v1
kind: Service
metadata:
  name: k8s-obs-app
  namespace: app-production
  labels:
    app: k8s-obs-app
    # This label is used by the ServiceMonitor's selector to discover this Service
    monitoring: "true"
spec:
  type: ClusterIP
  selector:
    # Must match the pod labels in the Deployment template
    app: k8s-obs-app
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
